setwd("C:/Users/alhayes/Desktop/salish/analysis")
load("twitter_all.RData")
load("twitter_NoRT.RData")
load("NetworkReady.RData")
load("net_twitter_mat.RData")
load("hyperlinksICL2.RData")
load("netHypIC2.RData")

require(statnet)
require(sna)
require(scales)

#Network-level statistics: Degree distributions
ideg_net <- degree(net, cmode = "indegree")
ideg_net_hypIC2 <- degree(net_hypIC2, cmode = "indegree")
ideg_net_twitter_mat <- degree(net_twitter_mat, cmode = "indegree")
ideg_hypIC2 <- degree(hypIC2, cmode = "indegree")
ideg_twitterAll <- degree(twitter_all, cmode = "indegree")
ideg_twitterNoRT <- degree(twitter_NoRT, cmode = "indegree")
odeg_net <- degree(net, cmode = "outdegree")
odeg_net_hypIC2 <- degree(net_hypIC2, cmode = "outdegree")
odeg_net_twitter_mat <- degree(net_twitter_mat, cmode = "outdegree")
odeg_hypIC2 <- degree(hypIC2, cmode = "outdegree")
odeg_twitterAll <- degree(twitter_all, cmode = "outdegree")
odeg_twitterNoRT <- degree(twitter_NoRT, cmode = "outdegree")


plot(table(ideg_net)/length(ideg_net), type = "l", lwd = 1.7, xaxs = "i", xaxt = "n", yaxt = "n", yaxs = "i", xlim = c(0,35), ylim = c(0,.3), ylab = "Density", main = "in-degree distribution", bty = "n")
lines(table(ideg_hypIC2)/length(ideg_hypIC2), type = "l", col = "red", lwd = 1.7)
axis(side = 2, at = c(0, 0.1, 0.2, 0.3))
abline(h = 0, col = "gray50")
legend("topright", legend = c("survey", "hyperlink"), text.col = c("black", "red"), bty = "n")

plot(table(odeg_net)/length(odeg_net), type = "l", lwd = 1.7, xaxs = "i", xaxt = "n", yaxt = "n", yaxs = "i", xlim = c(0,35), ylim = c(0,.3), main = "out-degree distribution", bty = "n")
lines(table(odeg_hypIC2)/length(odeg_hypIC2), type = "l", col = "red", lwd = 1.7)
abline(h = 0, col = "gray50")
abline(v = 0, col = "gray50")
#lines(table(odeg_twitterAll)/length(odeg_twitterAll), type = "l", col = "blue", lwd = 1.5)
#lines(table(odeg_twitterNoRT)/length(odeg_twitterNoRT), type = "l", col = "blue", lwd = 1.7)
#axis(side = 1, at = c(5, 10, 15, 20, 25, 30))
#legend("topright", legend = c("survey", "hyperlink"), text.col = c("black", "red"), bty = "n")

par(mar = c(2,2,0,0))
plot(table(ideg_net)/length(ideg_net), type = "l", lwd = 1.7, xaxs = "i", xaxt = "n", yaxt = "n", yaxs = "i", xlim = c(0,35), ylim = c(0,.3), ylab = "Density", bty = "n")
#lines(table(ideg_hypIC2)/length(ideg_hypIC2), type = "l", col = "red", lwd = 1.7)
lines(table(ideg_twitterAll)/length(ideg_twitterAll), type = "l", col = "blue", lwd = 1.5)
lines(table(ideg_twitterNoRT)/length(ideg_twitterNoRT), type = "l", col = "cyan", lwd = 1.7)
axis(side = 1, at = c(0, 5, 10, 15, 20, 25, 30))
axis(side = 2, at = c(0, 0.1, 0.2))
legend("topright", legend = c("survey", "twitter(all)", "twitter(noRT)"), text.col = c("black", "blue", "cyan"), bty = "n")

par(mar = c(2,0.5,0,0))
plot(table(odeg_net)/length(odeg_net), type = "l", lwd = 1.7, xaxs = "i", xaxt = "n", yaxt = "n", yaxs = "i", xlim = c(0,35), ylim = c(0,.3), bty = "n")
#lines(table(odeg_hypIC2)/length(odeg_hypIC2), type = "l", col = "red", lwd = 1.7)
lines(table(odeg_twitterAll)/length(odeg_twitterAll), type = "l", col = "blue", lwd = 1.5)
lines(table(odeg_twitterNoRT)/length(odeg_twitterNoRT), type = "l", col = "cyan", lwd = 1.7)
abline(v = 0, col = "gray50")
axis(side = 1, at = c(0, 5, 10, 15, 20, 25, 30))
#legend("topright", legend = c("survey", "hyperlink"), text.col = c("black", "red"), bty = "n")

dev.off()


#node-level statistics
pdf("degree scatterplot.pdf", width = 6, height = 6)
par(mfrow=c(2, 2), mar = c(0,2,2,0))
plot(jitter(ideg_hypIC2), jitter(ideg_net_hypIC2), main="in-degree", col = alpha("red", 0.5), pch = 20, xaxs = "i", xaxt = "n", yaxt = "n", cex = .7, bty = "n",
     xlim= c(0, 2+max(ideg_hypIC2, ideg_net_hypIC2)), ylim = c(0, 2+max(ideg_hypIC2, ideg_net_hypIC2)), xaxs = "i", yaxs = "i")
abline(a = 0, b = 1, col = "gray50")
abline(h = 0, col= "gray50")
abline(v = 0, col= "gray50")
text(40,42, "45-degree line", cex = .7, col = "gray50", srt = 45)
mtext("survey", side = 2)
par(mar = c(0,0.5,2,0))
plot(jitter(odeg_hypIC2), jitter(odeg_net_hypIC2), main="out-degree",col = alpha("red", 0.5), pch = 20, xaxs = "i", xaxt = "n", yaxt = "n", cex = .7, bty = "n",
     xlim=c(0, 2+max(odeg_hypIC2, odeg_net_hypIC2)), ylim = c(0, 2+max(odeg_hypIC2, odeg_net_hypIC2)), xaxs = "i", yaxs = "i")
abline(a = 0, b = 1, col = "gray50")
abline(h = 0, col= "gray50")
abline(v = 0, col= "gray50")
legend("topleft", legend = "hyperlink", text.col = "red", bty = "n")
par(mar = c(2,2,0,0))
plot(jitter(ideg_twitterAll), jitter(ideg_net_twitter_mat), col = alpha("blue", 0.5), pch = 20, xaxs = "i", xaxt = "n", yaxt = "n", cex = .7, bty = "n",
     xlim= c(0, 2+max(ideg_twitterAll, ideg_net_twitter_mat)), ylim = c(0, 2+max(ideg_twitterAll, ideg_net_twitter_mat)), xaxs = "i", yaxs = "i")
points(jitter(ideg_twitterNoRT), jitter(ideg_net_twitter_mat), pch = 20, col = alpha("cyan", 0.5), cex = .7)
abline(a = 0, b = 1, col = "gray50")
abline(h = 0, col= "gray50")
abline(v = 0, col= "gray50")
mtext("survey", side = 2)
mtext("online network", side = 1)
par(mar = c(2,0.5,0,0))
plot(jitter(odeg_twitterAll), jitter(odeg_net_twitter_mat), col = alpha("blue", 0.5), pch = 20, xaxs = "i", xaxt = "n", yaxt = "n", cex = .7, bty = "n",
     xlim= c(0, 2+max(odeg_twitterAll, odeg_net_twitter_mat)), ylim = c(0, 2+max(odeg_twitterAll, odeg_net_twitter_mat)), xaxs = "i", yaxs = "i")
points(jitter(odeg_twitterNoRT), jitter(odeg_net_twitter_mat), pch = 20, col = alpha("cyan", 0.5), cex = .7)
abline(a = 0, b = 1, col = "gray50")
abline(h = 0, col= "gray50")
abline(v = 0, col= "gray50")
legend("topleft", legend = c("twitter(all)", "twitter(no RT)"), text.col = c("blue", "cyan"), bty = "n")
mtext("online network", side = 1)
dev.off()


#betweenness centrality
bet_netT <- betweenness(net_twitter_mat)
bet_netH <- betweenness(net_hypIC2)
bet_Tall <- betweenness(twitter_all)
bet_Tnort <- betweenness(twitter_NoRT)
bet_hypIC2 <- betweenness(hypIC2)

pdf("between scatterplot.pdf", width = 6, height = 3)
par(mfrow=c(1, 2), mar = c(2,2,2,0))
plot(bet_hypIC2, bet_netH, xlab="Hyperlink betweenness", ylab="Survey betweenness", col = alpha("red", 0.5), pch = 20,
     xlim = c(0, 100+max(bet_hypIC2)), ylim=c(0, 100+max(bet_netH)), xaxs = "i", yaxs = "i", xaxt = "n", yaxt = "n", cex = .7, bty = "n")
abline(h=0, col = "gray50")
abline(v=0, col = "gray50")
mtext("survey betweenness", side = 2)
mtext("hyperlink betweenness", side = 1)
legend("topleft", legend = "hyperlink", text.col = "red", bty = "n")
par(mar = c(2,0.5,2,0))
plot(bet_Tall, bet_netT, xlab="Twitter betweenness", ylab="Survey betweenness", col = alpha("blue", 0.5), pch = 20,
     xlim = c(0, 100+max(bet_Tall, bet_Tnort)), ylim=c(0, 100+max(bet_netT)), xaxs = "i", yaxs = "i", xaxt = "n", yaxt = "n", cex = .7, bty = "n")
points(bet_Tnort, bet_netT, col = alpha("cyan", 0.5), pch = 20)
legend("topleft", legend = c("twitter(all)", "twitter(no RT)"), text.col = c("blue", "cyan"), bty = "n")
abline(h=0, col = "gray50")
abline(v=0, col = "gray50")
mtext("twitter betweenness", side = 1)
dev.off()
